### ISSUE TITLE
yeah buddy

### ISSUE THREAD

**Issue by zek-c** [FlamePVPCodes/SecurlyKiller3000#1]
if you're gonna steal code don't have my name written all over it

**Comment by FlamePVPCodes** [comment]
I'm not like that . I'm the best 12-year-old  coder. I won't steal code I love helping other coders like me.

**Comment by zek-c** [comment]
you are like that because you stole this from me. everything you "coded" is straight up stolen... you can't code. stop lying and realize that you are awful skid that cant code and steals everything. this is literally mine, you don't even know any coding language at all

**Comment by FlamePVPCodes** [comment]
By the way it was an accident because you see I had that idea in my head but when i went to search there was already one I got sad and stole it my bad bro ill give u credit

**Comment by FlamePVPCodes** [comment]
There I gave you credits

**Comment by FlamePVPCodes** [comment]
even ur link to page to follow

**Comment by FlamePVPCodes** [comment]
can i be forgiven im sorry. Can we like calaborate I know how to create guis and stuff

**Comment by FlamePVPCodes** [comment]
i know how to crate html, javascript, css websites plz

**Comment by zek-c** [comment]
no you don't lmaooo let me see you make a website then but don't steal it also this is literally my code and all of the other repos are my code and i can't even spell so i can't even code

**Comment by zek-c** [comment]
i see you changed it to say it was made by you and me, it was not made by you it was only me. i came up with the idea not you, i don't even know you so stop stealing my code.

**Comment by FlamePVPCodes** [comment]
Ill create a website for u what name I love helping ppl

**Comment by zek-c** [comment]
dude just delete the repo it's not yours stop taking credit for it you didn't come up with the idea, you don't even know how this code works.

**Comment by FlamePVPCodes** [comment]
Yeah i dont know how ur code works but ik how javascript css and html works :)

**Comment by zek-c** [comment]
you say you know javascript but not how my code works but my code is javascript and it's literally just fetch() which means you know nothing of javascript and you don't know how to make ur own website bc all u have is stolen websites that you put your name on lol

**Comment by zek-c** [comment]
btw i reported and dmca filed so have fun with law enforcement

**Comment by FlamePVPCodes** [comment]
im 12

**Comment by FlamePVPCodes** [comment]
U sure i stole websites i use vercel.com to host my website I make eaglercraft client here: flameclientwb.vercel.app I made

**Comment by zek-c** [comment]
since you're 12 they will just fine your parents $1000 instead lol and also your websites ARE stolen you just host them yourself u don't write the code

**Comment by FlamePVPCodes** [comment]
U sure

**Comment by FlamePVPCodes** [comment]
HAAHAHAHHAAHAHHAHHA

**Comment by FlamePVPCodes** [comment]
I can code

**Comment by FlamePVPCodes** [comment]
u think i dont write code but u dont relize my dad is a police officer

**Comment by FlamePVPCodes** [comment]
I go to coding school everyday after my real school
💀

**Comment by zek-c** [comment]
just bc your dads an officer doesn't mean you can escape legal trouble, if only it will make it worse because he will punish you worse personally

**Comment by zek-c** [comment]
and u seem to be panicking because i said that by replying a lot

**Comment by FlamePVPCodes** [comment]
LOL

**Comment by zek-c** [comment]
Without your compliance to remove the repository, i waited the required time at notice and now a dmca has been filed lol

**Comment by FlamePVPCodes** [comment]
Oh ok. :)
